
var C_MSG = 
{
"1" : "Are you sure to disconnect?",
"2" : "Login failed: name and password cannot be empty.",
"3" : "Disconnected!",
"4" : "Connection is closed.",
"5" : "Connecting ...",
"6" : "Connection error",
"7" : "Server is not available.",
"8" : "Connection closed by server.",
"9" : "Connect",
"10" : "Disconnect",
"11" : "please provide a room name",
"12" : "You are not in a room, text is not sent: ",
"13" : "Type @rooms for room list, @create {room} to create room, @join {room} to join a room, @help for more.",
"14" : "you are in room: ",
"15" : "please provide a user name",
"16" : "you have no permission for this operation",
"17" : "please provide max room size (0 or positive integer)",
"18" : " is not an integer.",
"19" : "Connection not opened",
"20" : "Register failed: name and password cannot be empty.",
"21" : "Register failed: two passwords do not match.",
"22" : "Password cannot be empty.",
"23" : "Two passwords do not match.",
"24" : "Are you sure to log out?",
"25" : "You are not in any room yet.",
"26" : "Please select a room to join",
"27" : " invited you to join room ",
"28" : " accepted your invitation.",
"29" : " rejected your invitation.",
"30" : " will accept your invitation later.",
"31" : "User ",
"32" : " entered room.",
"33" : " left room.",
"34" : "New room ",
"35" : " is created.",
"36" : "Room ",
"37" : " is gone.",
"38" : " logs in.",
"39" : " is disconnected.",
"40" : " logs out.",
"41" : " appointed you as the new room master.",
"42" : "You are kicked out of the room ",
"43" : " is kicked out",
"44" : "Room max size is changed to ",
"45" : "false register response. abort.",
"46" : "You are registered. Now you can log in.",
"47" : "Register failed: ",
"48" : "false login response. abort.",
"49" : "User: ",
"50" : "You are logged in.",
"51" : "Invalid login name or password.",
"52" : "Error: ",
"53" : "Your password is updated.",
"54" : "Error when get room list: ",
"55" : "current room users: ",
"56" : "room '",
"57" : "' users: ",
"58" : "failed: ",
"59" : "You left room ",
"60" : "Room: ",
"61" : "You created and entered room ",
"62" : "Error happened when invite user to join.",
"63" : "You invited ",
"64" : " to join.",
"65" : "You accepted invitation of ",
"66" : " to join room ",
"67" : "You rejected invitation of ",
"68" : "You will accept invitation of ",
"69" : " later.",
"70" : "invalid invite reply message.",
"71" : "You set room master to ",
"72" : "You set the max size of this room to ",
"73" : "You set this room to ",
"74" : "public",
"75" : "private",
"76" : "invalid room name.",
"77" : "You entered room ",
"78" : "Error sending message ",
"79" : "You are logged out.",
"80" : "You are already in room ",
"81" : "Username",
"82" : "Password",
"83" : "Password (repeat)",
"84" : "Old Password",
"85" : "New Password",
"86" : "New Password (repeat) ",
"87" : "Are you sure to clear chat history?",
};
